### ISSUE TITLE
Exposure duration counting is rather inaccurate

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#558] opened 2018-08-25 19:12 UTC
Inspecting logs on PAN006 for last night, I noticed that the count-up for the first full length (120s) exposure only reaches 90 seconds, but did so at almost 120 seconds from the start.

```
D0825 00:57:40.368 observatory.py:263   Exposing for camera: Cam00
D0825 00:57:40.369 camera.py:442        image_id: Panoptes Unit PAN006 @ Wheaton College_6575fc_20180825T005740
D0825 00:57:40.369 canon_gphoto2.py:124 Taking 120.0 second exposure on Cam00: /var/panoptes/images/fields/HatP1/6575
fc/20180825T005549//20180825T005740.cr2
D0825 00:57:40.374 observatory.py:263   Exposing for camera: Cam01
D0825 00:57:40.375 camera.py:442        image_id: Panoptes Unit PAN006 @ Wheaton College_7bab97_20180825T005740
D0825 00:57:40.375 canon_gphoto2.py:124 Taking 120.0 second exposure on Cam01: /var/panoptes/images/fields/HatP1/7bab
97/20180825T005549//20180825T005740.cr2
D0825 00:57:40.380 observing.py:25      Waiting for images: 0.0 seconds
D0825 00:57:59.929 observing.py:25      Waiting for images: 15.0 seconds
D0825 00:58:18.926 observing.py:25      Waiting for images: 30.0 seconds
D0825 00:58:37.925 observing.py:25      Waiting for images: 45.0 seconds
D0825 00:58:56.909 observing.py:25      Waiting for images: 60.0 seconds
D0825 00:59:15.948 observing.py:25      Waiting for images: 75.0 seconds
D0825 00:59:34.945 observing.py:25      Waiting for images: 90.0 seconds
D0825 00:59:47.730 camera.py:241        Processing Panoptes Unit PAN006 @ Wheaton College_6575fc_20180825T005740
D0825 00:59:47.731 camera.py:244        Extracting pretty image
D0825 00:59:47.741 canon_gphoto2.py:154 Converting CR2 -> FITS: /var/panoptes/images/fields/HatP1/6575fc/20180825T005549//20180825T005740.cr2
D0825 00:59:48.016 camera.py:241        Processing Panoptes Unit PAN006 @ Wheaton College_7bab97_20180825T005740
D0825 00:59:48.016 camera.py:244        Extracting pretty image
```

I suspect a simple fix to pocs/state/states/default/observing.py will suffice.

**Comment by wtgee** [comment] 2018-08-25 21:11
Duplicate of #348.

**Closed by wtgee** 2018-08-25 21:11 UTC
