### ISSUE TITLE
Drop Voltage to Amps conversion in telemetry board code

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#276] opened 2017-12-30 14:55 UTC
(Moved from PACE repo.)

The conversion in the telemetry board sketch from the analogRead value (voltage) to amps on the 4 current sensed lines forces us to modify the sketch for each installation. We should do that on the NUC with a yaml file instead.

**Comment by wtgee** [comment] 2017-12-31 10:00
Duplicate of #126, closing.

**Closed by wtgee** 2017-12-31 10:00 UTC
