### ISSUE TITLE
Import error while taking individual tests.

### ISSUE THREAD

**Issue by kmeagle1515** [panoptes/POCS#825] opened 2019-04-16 18:54 UTC
#793 RELATED ISSUE
**Screenshots**
![Screenshot from 2019-04-17 00-20-21](https://user-images.githubusercontent.com/46345142/56236389-1a62d380-60a7-11e9-8a88-87919ec7c05e.png)

I did set env variables in the profile.d as well

**Comment by kmeagle1515** [comment] 2019-04-18 16:13
@wtgee @jamessynge i am getting this import error while running individual tests on my machine. This issue was earlier faced by @ImmortalRabbit  but he solved it by properly setting env variables. 
But i have set those in my etc/profile.d/new.sh file so that is not an issue for me i suppose.

**Comment by AnthonyHorton** [comment] 2019-05-24 07:01
Looks like the problem is due to not running tests from the top level directory of the repo (therefore no invoking conftest) and running `pytest` on a Python file that isn't a test file. Closing as not a bug.

**Closed by AnthonyHorton** 2019-05-24 07:01 UTC
